version: "3.9"

services:
  # Service for your Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hajir-app
    ports:
      - "3000:80"

  # Service for Nginx
  nginx:
    image: nginx:alpine
    container_name: hajir-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
